version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devin-clone-postgres
    environment:
      POSTGRES_USER: devin
      POSTGRES_PASSWORD: devin
      POSTGRES_DB: devin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devin -d devin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devin-network

  redis:
    image: redis:7-alpine
    container_name: devin-clone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devin-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: devin-clone-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - devin-network

  backend:
    build:
      context: ./backend/core
      dockerfile: Dockerfile
    container_name: devin-clone-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here-please-change-in-production
      - DATABASE_URL=postgresql+asyncpg://devin:devin@postgres:5432/devin
      - REDIS_URL=redis://redis:6379/0
      - ANTHROPIC_API_KEY=your-anthropic-api-key-here
      - DEBUG=True
      - PROJECT_NAME=Devin Clone MVP
      - VERSION=0.1.0
      - API_V1_STR=/api/v1
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000","http://frontend:3000"]
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAILS_FROM_EMAIL=noreply@devinclone.com
      - EMAILS_FROM_NAME=Devin Clone
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      - devin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devin-clone-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-here-please-change-in-production
    depends_on:
      - backend
    networks:
      - devin-network

volumes:
  postgres-data:
  redis-data:

networks:
  devin-network:
    driver: bridge